name: flutter_sound
version: 5.0.1
description: Flutter plugin that relates to sound like audio and recorder.
#author: dooboolab<dooboolab@gmail.com>
homepage: https://github.com/dooboolab/flutter_sound
environment:
    sdk: ">=1.19.0 <3.0.0"
    flutter: ">=1.12.0 <2.0.0"
dependencies:
  path_provider: ">=1.0.0 <2.0.0"
  logger: ^0.7.0+2
  intl: ^0.16.1
  recase: ^2.0.1
  uuid: ^2.0.4
  provider: ^4.1.0
  flutter_spinkit: ^4.0.0
  path: ">=1.0.0 <2.0.0"
  flutter:
    sdk: flutter
  #permission_handler: ">=5.0.0 <6.0.0"
  #flutter_ffmpeg: ">=0.2.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  #pedantic: ^1.9.0
  effective_dart: ^1.0.0
  #lint: ^1.1.1



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.dooboolab.fluttersound
        pluginClass: Flauto
      ios:
        pluginClass: Flauto
    ##androidPackage: com.dooboolab.fluttersound
    ##pluginClass: Flauto


    #androidPackage: xyz.canardoux.flauto
    #pluginClass: FlutterSoundPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
