name: example
description: Driver for the various Flutter Sound examples

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 7.8.4

homepage: https://github.com/canardoux/tau/blob/master/flutter_sound/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"



dependencies:
  flutter:
    sdk: flutter

# ============================================================================
# The following instructions are just for developing/debugging Flutter Sound
# Do not put them in a real App
#  flutter_sound_platform_interface: 7.8.4
#    path: ../../flutter_sound_platform_interface # flutter_sound_platform_interface Dir
#  flutter_sound_web: 7.8.4
#    path: ../../flutter_sound_web # flutter_sound_web Dir
  flutter_sound: ^7.8.4
#    path: ../ # Flutter Sound Dir
# ============================================================================


  cupertino_icons: ^0.1.3
  path_provider: ^1.6.27
  permission_handler: ^5.0.1
  path: ^1.6.4
  #flutter_ffmpeg: ^0.3.1
  intl: ^0.16.1



dev_dependencies:
 # flutter_test:
#    sdk: flutter
  pedantic: ^1.9.0
  effective_dart: ^1.0.0
  #lint: ^1.1.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - res/icons/ic_play.png
  - res/icons/ic_play_disabled.png
  - res/icons/2.0x/ic_play.png
  - res/icons/3.0x/ic_play.png
  - res/icons/ic_stop.png
  - res/icons/ic_stop_disabled.png
  - res/icons/2.0x/ic_stop.png
  - res/icons/3.0x/ic_stop.png
  - res/icons/ic_pause.png
  - res/icons/ic_pause_disabled.png
  - res/icons/2.0x/ic_pause.png
  - res/icons/3.0x/ic_pause.png
  - res/icons/ic_mic.png
  - res/icons/ic_mic_disabled.png
  - res/icons/2.0x/ic_mic.png
  - res/icons/3.0x/ic_mic.png
  - res/icons/ic_volume_down.png
  - res/icons/2.0x/ic_volume_down.png
  - res/icons/3.0x/ic_volume_down.png
  - res/icons/ic_volume_up.png
  - res/icons/2.0x/ic_volume_up.png
  - res/icons/3.0x/ic_volume_up.png

  - assets/
  - assets/samples/
  - assets/noises/
  - assets/extract/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
