name: flutter_sound_web
version: 7.8.4
description: Flutter plugin that relates to sound like audio and recorder.
#author: dooboolab<dooboolab@gmail.com>
homepage: https://github.com/dooboolab/flutter_sound
environment:
    sdk: ">=2.1.0 <3.0.0"
    flutter: ">=1.12.0"

# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSoundPlugin
        fileName: flutter_sound_web.dart
  assets:
  - js/
  - js/howler/
  - js/howler/howler.js
  - js/flutter_sound/
  - js/flutter_sound/flutter_sound.js
  - js/flutter_sound/flutter_sound_player.js
  - js/flutter_sound/flutter_sound_recorder.js


dependencies:
  flutter_sound_platform_interface: 7.8.4
#    path: ../flutter_sound_platform_interface # Flutter Sound Dir
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  js: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

